spring.application.name=billing-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/billing_service_db
spring.datasource.username=root
spring.datasource.password=SG7966.cgi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.redis.host=localhost
spring.redis.port=6379


spring.kafka.bootstrap-servers=localhost:9092
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
